import './styles/details.scss';
import './scripts/likeRating.js';
import '../node_modules/ion-rangeslider/css/ion.rangeSlider.min.css';
import '../node_modules/air-datepicker/dist/css/datepicker.min.css';
//import '../node_modules/air-datepicker/dist/js/datepicker.js';
import '../src/scripts/fsdDatepicker';
import './components/UIKit/modules/dropdown/dropDownGuests';
import './scripts/expandableCL.js';
import './components/UIKit/modules/burger/burger.js';
$('#d3').fsdDatepicker({ todayButton: true, clearButton: true });
$('#d4').fsdDatepicker({ todayButton: true, clearButton: true });